### ISSUE TITLE
Does not work removal customer

### ISSUE THREAD

**Issue by ruslann** [EduardoPires/EquinoxProject#10]
Good afternoon.
Does not work removal Customers. The necessary rights to delete were issued when the user was created: 

public async Task<IActionResult> Register(RegisterViewModel model, string returnUrl = null)
{
....
      user.Claims.Add(new IdentityUserClaim<string>
                {
                    ClaimType = "Customers",
                    ClaimValue = "Write"
                });
      user.Claims.Add(new IdentityUserClaim<string>
                {
                    ClaimType = "Customers",
                    ClaimValue = "Remove"
                });
....
}
But when you delete Customers, redirect to the page "Access Denied". 
If calls are rearranged in places, create a new user, logs in under it, then deletion starts to work, but creation and editing does not work.

**Comment by EduardoPires** [comment]
Please check if the table AspNetUserClaims have the both claims. Due the validation logic the claims need to be together like "Write,Remove" in the same claim.

So you need:
user.Claims.Add(new IdentityUserClaim
{
ClaimType = "Customers",
ClaimValue = "Write,Remove"
});

**Comment by ruslann** [comment]
Thanks.
