### ISSUE TITLE
Solution can not be load in VS 2017(V15.7.4)

### ISSUE THREAD

**Issue by Andy-Yin** [EduardoPires/EquinoxProject#100]
Solution can not be load in VS 2017(V15.7.4)

**Comment by brunohbrito** [comment]
Maybe it's a bug inside Global.json

Open file Global.json and remove Sdk property
Old:
`
{
  "projects": [ "src", "test" ],
  "sdk": {
    "version": "2.1.200"
  }
}
`
New:
`
{
  "projects": [ "src", "test" ]
}
`

**Comment by Andy-Yin** [comment]
thanks, fixed!
