### ISSUE TITLE
Why use mediatR in application service?

### ISSUE THREAD

**Issue by marcrib** [EduardoPires/EquinoxProject#101]
Hi

It is common to use MediatR (used for CQRS implementation) for replace Application Service
I understand that CQRS is an orchestration layer for data access

1 - Why not use direct MediatR in Controller?
2 - What advantage use MediatR in application services?

Anyone to explain me?

**Comment by alexsandro-xpt** [comment]
Maybe for an abstraction. That is it @EduardoPires ?

**Comment by thiagolunardi** [comment]
Decoupling is the answer. Controller is not responsible for firing messages or alike. It must just validate the request and then forward its command to the proper service. Also it's not nice to spread your application components over layers.

**Comment by marcrib** [comment]
@thiagolunardi Where this rule written? Any link for me read?

All examples using MediatR is called in Controller

**Comment by thiagolunardi** [comment]
Yes, but just for example purpose.
In examples, everything is possible to accomplish just inside one action controller. You can validate, add business rules, open connection to database, send emails, write file to disc, etc. But, should you? Is it a good practice?

**Comment by marcrib** [comment]
@thiagolunardi What is the difference between these two classes?
```

public class FooService 
{
   public IMediator _mediator;
   public void Method(Command cmd)
   {
       _mediator.Send(cmd);
    }
}
```
and
```
public class FooHandler : IRequestHandler<Command>
{
    public Task Handler(Command cmd)
    { 
              _repo.Create(cmd);
    }
}
```
both are abstraction, both receive command class

I'm not reclaim, but I want to understand why was used command in application service

**Comment by marcrib** [comment]
@alexsandro-xpt abstraction of abstraction?

**Comment by marcrib** [comment]
@thiagolunardi  You to be contradicting yourself, ok

**Comment by alexsandro-xpt** [comment]
@marcrib in this project will appear abstraction of abstraction, but in another case when the web layer is replaced, it's not be an abstraction of abstraction any more.

**Comment by Necronux** [comment]
https://stackoverflow.com/questions/50834935/replacing-service-layer-with-mediatr-is-it-worth-to-do-it/51985482#51985482
