### ISSUE TITLE
custom login path didn't work

### ISSUE THREAD

**Issue by liugt34** [EduardoPires/EquinoxProject#104]
in startip.cs file
// This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddUEditorService();
            services.AddIdentity<AdvertUser, IdentityRole>().AddEntityFrameworkStores<AdvertDbContext>().AddDefaultTokenProviders();
            services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme)
                    .AddCookie(o =>
                    {
                        o.LoginPath = "/admin/account/login";
                        o.AccessDeniedPath = "/admin/account/accessdenied";
                    });

            services.AddMvc();

			Bootstrapper.RegisterServices(services);
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseBrowserLink();
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
            }

            app.UseStaticFiles();

			app.UseAuthentication();

            app.UseMvc(routes =>
            {
				routes.MapAreaRoute(
                    name: "AdvAdmin",
					areaName:"Admin",
                    template: "Admin/{controller=Home}/{action=Index}/{id?}");

                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });
        }

but when i get the authorized page ,it still use the default login path  "/account/login"

**Comment by EduardoPires** [comment]
Did you decorated the controllers with this new attribute?
