### ISSUE TITLE
CustomerHistory doesn't work

### ISSUE THREAD

**Issue by Troom** [EduardoPires/EquinoxProject#107]

**Comment by rpucia** [comment]
I wonder if it is thread safe. I think there should be non-static methods or any "lock" in ToJavaScriptCustomerHistory method

**Comment by Abdulhameed-A** [comment]
You probably need to resolve the port number in the url, at line `100 (the ajax request)` in `EquinoxProject\src\Equinox.UI.Site\Views\Customer`
