### ISSUE TITLE
Registering Mappings in AutoMapperSetup.cs, what it really means?

### ISSUE THREAD

**Issue by alexsandro-xpt** [EduardoPires/EquinoxProject#108]
The `AutoMapperConfig.RegisterMappings();` will works only under assembly that which was declared/defined?

https://github.com/EduardoPires/EquinoxProject/blob/3ff7f9f158e36090edf22bdb1d5ea69496224825/src/Equinox.WebApi/Configurations/AutoMapperSetup.cs#L16-L18

**Comment by jedielson** [comment]
In this case, he is doing  [static configuration of AutoMapper.](https://automapper.readthedocs.io/en/latest/Getting-started.html#where-do-i-configure-automapper)

I think there is a [better approach](https://lostechies.com/jimmybogard/2016/07/20/integrating-automapper-with-asp-net-core-di/) for Asp.Net Core, but I still suggest you to learn both.

0/

**Comment by EduardoPires** [comment]
The automatic registration only works if the profile classes is in ASP.NET application. So I have to call manually.
