### ISSUE TITLE
Migrations Problem

### ISSUE THREAD

**Issue by m2017atTR** [EduardoPires/EquinoxProject#11]
I am trying to use Migrations beside sql script
But migrations' some is in Equinox.Infra.CrossCutting.Identity and others in Equinox.Infra.Data

how to use them 

--- after afew try 

          dotnet ef database update --context  EquinoxContext  --startup-project ../Equinox.UI.Site
          
          dotnet ef database update --context  EventStoreSQLContext --startup-project ../Equinox.UI.Site

commands worked fine but what about 
           
          Infra.CrossCutting.Identity project migrations ?

regards

**Comment by EduardoPires** [comment]
Sorry I didn't understand. Could you give more details?

**Comment by m2017atTR** [comment]
Ok. Sorry.
Project is using EntityFramework , 

migrations could be done but 
there is more then one EF DbContext in Equinox.Infra.Data
I could do it succesfully but 
how to make EF data migrations for Equinox.Infra.CrossCutting.Identity project..

and second question is
How to change db choise if i want to use PostgreSql or MySql

thanks

**Comment by m2017atTR** [comment]
Ok. Got it...
ef migration contains startup project
and second is ;
Defining and injecting DBContexts done jobe succesfully.

thanks for this good work.
regards
