### ISSUE TITLE
Database initialisation fails.....

### ISSUE THREAD

**Issue by pomeara** [EduardoPires/EquinoxProject#113]
Hello, I have just found this application and though it would be great to use as a reference for learning new patterns and a new base application.

I was surprised CodeFirst was not used / automatic database creation rather than having to manually enter EF commands to get the database created and initialised. 

When running the Update-Database command I get the following error when using a new database.  Can you include DB setup guides (if I'm dong things wrong - quite possible !) or can you please advise.

-- trace of command that fails --

Failed executing DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
CREATE TABLE [AspNetUsers] (
    [Id] nvarchar(450) NOT NULL,
    [AccessFailedCount] int NOT NULL,
    [ConcurrencyStamp] nvarchar(max) NULL,
    [Email] nvarchar(256) NULL,
    [EmailConfirmed] bit NOT NULL,
    [LockoutEnabled] bit NOT NULL,
    [LockoutEnd] datetimeoffset NULL,
    [NormalizedEmail] nvarchar(256) NULL,
    [NormalizedUserName] nvarchar(256) NULL,
    [PasswordHash] nvarchar(max) NULL,
    [PhoneNumber] nvarchar(max) NULL,
    [PhoneNumberConfirmed] bit NOT NULL,
    [SecurityStamp] nvarchar(max) NULL,
    [TwoFactorEnabled] bit NOT NULL,
    [UserName] nvarchar(256) NULL,
    CONSTRAINT [PK_AspNetUsers] PRIMARY KEY ([Id])
);
System.Data.SqlClient.SqlException (0x80131904): There is already an object named 'AspNetUsers' in the database.

**Comment by TeoDanilo** [comment]
Have you took a look at the folowing issue?
https://github.com/EduardoPires/EquinoxProject/issues/77

Looks like that table are in the both migration of Identity layer. I fixed that removing the migration and adding it again.

>remove-migration
Then
>add-migration Initial
