### ISSUE TITLE
System.InvalidOperationException

### ISSUE THREAD

**Issue by rajdoshi9089** [EduardoPires/EquinoxProject#114]
I am getting error like this. Please help me out. it cause error when update record.

'Handler was not found for request of type MediatR.IRequestHandler`2[MineLife.Domain.Commands.UpdateCustomerCommand,MediatR.Unit]. Register your handlers with the container. See the samples in GitHub for examples.'
![capture](https://user-images.githubusercontent.com/43923877/46579333-b04ce000-ca2c-11e8-8e19-3c0a069b459d.PNG)

**Comment by EduardoPires** [comment]
Seems like your command is not registered, but I never saw this error in my solution. Try the new version.
