### ISSUE TITLE
Version 2.0

### ISSUE THREAD

**Issue by VitalyV** [EduardoPires/EquinoxProject#115]
Hi Eduardo,

What about Equinox 2.0?
Are you working on this version?

Thanks

**Comment by thiagozulato** [comment]
@VitalyV Yes, you can see the roadmap here https://github.com/EduardoPires/EquinoxProject/wiki/RoadMap

**Comment by EduardoPires** [comment]
Hi @VitalyV yes! I'm working. Slowly but working.
