### ISSUE TITLE
Problem to read Related Data

### ISSUE THREAD

**Issue by TeoDanilo** [EduardoPires/EquinoxProject#117]
I can't use ".Include" in CustomerController, and don't know how to do read related data without using it.

CustomerController is like this

            var customerViewModel = _customerAppService.GetById(id.Value);

            if (customerViewModel == null)
            {
                return NotFound();
            }

            return View(customerViewModel);

I would like to use something like this:

            var customerViewModel  = _context.Customers
                .Include(s => s.SomeRelatedTable);

            if (customerViewModel == null)
            {
                return NotFound();
            }

            return View(customerViewModel);

But got error because its not assignable to a viewModel.

trying use like that:

            var customerViewModel = _customerAppService.GetById(id.Value)
            .Include(s => s.SomeRelatedTable);

            if (customerViewModel == null)
            {
                return NotFound();
            }

            return View(customerViewModel);

But then CustomerViewModel does not have a defination to Include.

Can someonde help me with related data in this Archteture? 

My CustomerViewModel

        [Key]
        public Guid Id { get; set; }

        [Required(ErrorMessage = "The Name is Required")]
        [MinLength(2)]
        [MaxLength(100)]
        [DisplayName("Name")]
        public string Name { get; set; }

        [Required(ErrorMessage = "The E-mail is Required")]
        [EmailAddress]
        [DisplayName("E-mail")]
        public string Email { get; set; }

        [Required(ErrorMessage = "The BirthDate is Required")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        [DataType(DataType.Date, ErrorMessage = "Data em formato inválido")]
        [DisplayName("Birth Date")]
        public DateTime BirthDate { get; set; 

        public virtual ICollection<SomeRelatedTableViewModel> SomeRelatedTables { get; set; }

and SomeRelatedTableViewModel:

        [Key]
        public Guid Id { get; set; }

        [Required(ErrorMessage = "The Name is Required")]
        [MinLength(2)]
        [MaxLength(100)]
        [DisplayName("Name")]
        public string Name { get; set; }
      
        public Guid CustomerId { get; set; }

        public virtual Customer Customer { get; set; }

**Comment by andreluizsecco** [comment]
The "Include" method belong to Entity Framework Core and not to Controller or AppService.

To get data with related table you have create a method "GetById" in CustomerRepository class (Equinox.Infra.Data project) to override the default behavior in Repository class, like this:

```
public override Customer GetById(Guid id)
{
	return DbSet.
		.Include(c => c.SomeRelatedTable)
		.FirstOrDefault(c => c.Id == id);
}
```

**Comment by TeoDanilo** [comment]
@andreluizsecco 

It works perfectly! Thank you so much
