### ISSUE TITLE
Erro pra ver log history

### ISSUE THREAD

**Issue by Cesar1986BR** [EduardoPires/EquinoxProject#119]
estou com problema pra visualizar o log history, quando tento ver recebo esse erro no debugger:
http://prntscr.com/maca3m

e toda vez que insiro um novo custumer eleaté insere mas sempre  da erro :http://prntscr.com/macaoz
tem algo a mais que tenho que fazer?

obrigado

**Comment by EduardoPires** [comment]
Você criou a base corretamente com todos os mapeamentos?
