### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by di48l069** [EduardoPires/EquinoxProject#12]
Hello @EduardoPires  I have built my project around EquinoxProject was wondering can you help me with something?

**Comment by di48l069** [comment]
How would I generate ApplicationDbContextModelSnapshot.cs this via nuget console?

**Comment by vip32** [comment]
all nugets are restored by using 'dotnet restore'

**Comment by EduardoPires** [comment]
@di48l069 Running the EF command Update-Database all snapshots will be updated.

**Comment by di48l069** [comment]
@EduardoPires Thank you
