### ISSUE TITLE
[FEATURE] Alternative datastorage options

### ISSUE THREAD

**Issue by ghost** [EduardoPires/EquinoxProject#122]
Hi @EduardoPires,

Please could add alternative datastorage options such as `PostgreSQL`.

User can define which database they would like to use:
```
"ConnectionStrings": {
    "DefaultConnection": "Server=(localdb)\\mssqllocaldb;Database=Equinox;Trusted_Connection=True;MultipleActiveResultSets=true"
},
"EquinoxProject": {
    "DatabaseProvider": "PostgreSQL"
}
```

**Comment by EduardoPires** [comment]
After thinking about this design, I will let the user implement it on their own. Equinox is not a boiler plate, so it's better maintain the simplicity.
