### ISSUE TITLE
无法打开项目

### ISSUE THREAD

**Issue by ioer2008** [EduardoPires/EquinoxProject#132]
vs2019 已安装 core 2.2,但是打不开项目,请问该如何处理?

![image](https://user-images.githubusercontent.com/12724988/57421610-0f7f0700-723f-11e9-8dbb-8291cdbed5c6.png)

**Comment by TeoDanilo** [comment]
I do not know your language, so can't tell what the error says, but it seems to be problem with the SDK installed in your machine. You need to install the correct version or change the references. If you delet 'global.json' the project will open, but do this only to see the code, is NOT RECOMENDED to use a project withou the global.json rightly configured.

**Comment by sc1994** [comment]
![image](https://user-images.githubusercontent.com/22900800/57601141-48481480-758e-11e9-830a-02374f1fdc17.png) 我想这个错误信息给的非常详细了

**Comment by jedielson** [comment]
Could we use English here?

**Comment by sc1994** [comment]
Ok, My  think is that he cannot open the problem of the solution, which is explained in great detail in the exception list.
That's all I want to say
sorry for the inconvenience
I'm weak in English. 🤷
