### ISSUE TITLE
Lack of documentation

### ISSUE THREAD

**Issue by levalencia** [EduardoPires/EquinoxProject#14]
Hello Eduardo

I came across this github repo and its amazing, exactly what I was looking for.  However classes are not documented and for a person who doesnt know about DDD a lot then its hard to understand.

Can you please point me in the right direction of what to read first before I can understand your code.

I found these posts but they are quite old and not sure if you took some code from these blog posts (eg EntityBase)

https://dotnetcodr.com/architecture-and-patterns/

**Comment by EduardoPires** [comment]
You need to understand about DDD concepts (entity modeling, aggregates) CQRS concepts (commands, queries, bus), SOLID concepts (part of POO) and details about the frameworks and tools described in the main page. My advice: Read the book of the author Vaughn Vernon about DDD.
