### ISSUE TITLE
Why 2 migrations structure?

### ISSUE THREAD

**Issue by rhgm** [EduardoPires/EquinoxProject#141]
Hello and congratulations for the project!

I see in CrossCutting, 2 migrations structure, why?

**Comment by carloshenriqueribeiro** [comment]
in CossCutting only 1 migrations by ApplicationDbContext.

in Ifra/Data + 2 migrations
1 for event context and other for domain context

**Comment by rhgm** [comment]
I created same structure in my test project, and i execute Add-Migration -Context ApplicationDbContext InitialIdentity on console. The paste Migrations  exist only in Test.Infra.Identity, equals to EquinoxProject in Equinox.Infra.CrossCutting.Identity>Migrations.
The question is: do i need to worry about that? Migration in Equinox.Infra.CrossCutting.Identity>Data>Migrations is important?


<img src="https://qjtyvq.dm.files.1drv.com/y4mBVsZUBwpoJdRofmYciFEOGkH7YpiNbj7n0Q4jYqwYxGriyq17IKGslchRGbIlLd0IGQ6CtCDFlC7rAIs8jy2Oz_cynnodxaeDnzVBV7ekDOrKN9j10KX06Ci6LSW02LgLBztz38WuGPTXKxVNHctuhHOpHalMQcfihhuMQZPKiNrw-6FJUZkgJb8f1eOk_N_T5XGbvBL0oQ_DHr4vdcETQ?width=457&height=281&cropmode=none" width="457" height="281" />

**Comment by EduardoPires** [comment]
Isn't necessary. But you can keep migrations files if you want
