### ISSUE TITLE
Would like to have tutorials or detail explanation on the Event Sourcing. 

### ISSUE THREAD

**Issue by chhinsras** [EduardoPires/EquinoxProject#145]
This is really good cqrs and event sourcing sample, I ever since.

But this is quite confusing as i never implement event sourcing before, i did cqrs.

So, would you mind giving tutorials video or written showing how to write them based on this project

tahnk you

**Comment by guilhermesalvi** [comment]
Hello! I'm not the best person to explain, but basically every Command (data change) is sent to the Mediatr and it does the work delegating a task to handler. The handler trigger a event and at the end of the process, the event object is serialized and saved within the database.

**Comment by EduardoPires** [comment]
You can try this:
https://aka.ms/microservicesebook
