### ISSUE TITLE
Advise on handling Exceptions

### ISSUE THREAD

**Issue by gang89** [EduardoPires/EquinoxProject#147]
Hi guys,

Thanks for sharing this project with the community. Have benefited a lot from here just by studying and trying out the project structure.

Would like to clarify regarding the handling of exceptions for this project. It seems like any exceptions that are found in the domain layer is not able to be captured by a global exception. 

Example:
In one of my domain model constructor - I were to deliberate throw an exception 
<img width="692" alt="Screenshot 2019-10-20 at 6 36 28 PM" src="https://user-images.githubusercontent.com/32039249/67158269-97c61400-f368-11e9-9ba8-80e5604710fd.png">

I would expect it to be caught by a global exception handler such as below and returns an error
<img width="777" alt="Screenshot 2019-10-20 at 6 37 40 PM" src="https://user-images.githubusercontent.com/32039249/67158283-c348fe80-f368-11e9-8f08-0f083b3c5c97.png">

However, the API constantly returns a 200 OK success with no error message (probably because I didnt use the domainNotification Bus).

I also tried implementing along with GlobalExceptionFilter / Exception Middleware but to no avail. 
It seems like the system exceptions are not surfaced to the API project Exception Handlers.

Have been looking for solutions for a few days now. Hence any advise would be greatly appreciated.

Regards,

**Comment by Agnei** [comment]
Hello Eduardo,

I've implemented a middleware exceptions for .net core, maybe it sees great for the equinox project.

Follow attached the file. I hope it help you to improve your project.

At.,
Agnei Silva
________________________________

**Comment by EduardoPires** [comment]
@gang89  We try to avoid exceptions for known reasons. You can let validations do all the work and they will publish error notifications
