### ISSUE TITLE
Feature Request: ProblemDetails

### ISSUE THREAD

**Issue by brunohbrito** [EduardoPires/EquinoxProject#148]
There is a RFC about default response type for API's in case of error.

> Abstract
   This document defines a "problem detail" as a way to carry machine-
   readable details of errors in a HTTP response to avoid the need to
   define new error response formats for HTTP APIs.
 - [RFC 7807](https://tools.ietf.org/html/rfc7807)

And Microsoft has a default implementation in ASP.NET Core, [ProblemDetails](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.problemdetails?view=aspnetcore-3.0)

So instead return a custom object in BadRequest, it could return a ProblemDetails.

Why?
Support best practices

**Comment by EduardoPires** [comment]
Done at #161
