### ISSUE TITLE
Feature Request: Restfull Api support

### ISSUE THREAD

**Issue by brunohbrito** [EduardoPires/EquinoxProject#149]
There are several articles describing good practices around Restfull API's and how to deal with Responses in each scenario.

I'll address some references at the end.

ASP.NET Core support several different types of Response, e.g: 

* Ok()
* NoContent()
* BadRequest()
* CreatedAtAction()
* NotFound()

So Equinox could provide a more Restful approach by supporting some of these requests, instead of just Ok() and BadRequest() and also provide an example of Patch HTTP Verb.

For example, CreatedAtAction() is a perfect response for POST, because it provides a location header where data could be found.

Patch is a good way to prevent several Put methods, like: `UpdateName`, `UpdateMiddleName` etc.

* [Best Practices for Designing a Pragmatic RESTful API](https://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api#useful-post-responses)
* [HTTP Status Code](https://www.restapitutorial.com/httpstatuscodes.html)
* [Online Book - Representational State Transfer (REST)](https://www.ics.uci.edu/~fielding/pubs/dissertation/rest_arch_style.htm)

**Comment by EduardoPires** [comment]
Done at #161
