### ISSUE TITLE
Integration with .net core api (Dapper with mysql connector)

### ISSUE THREAD

**Issue by gtzinos** [EduardoPires/EquinoxProject#15]
I'm developing a Web API with .Net core api 1.1. After searching I can't find any document or sample that use authorization without the use of Entity Framework. Instead of this i need to use dapper with a mysql connector in order to connect my app with a mysql server. Is it possible to do it with your library ? If yes please can i have an example ?

**Comment by EduardoPires** [comment]
This is a sample project not a library. You can fork this project and implement Dapper with MySQL without problems.
