### ISSUE TITLE
Would it be possible to reconstruct view/query DB from event store

### ISSUE THREAD

**Issue by maxpavlov** [EduardoPires/EquinoxProject#151]
Hello. Before I dive into the architecture and implementation too deep, could someone what got acquainted with the Equinox suggest if as it is currently, it would be possible to reconstruct read DB from event store? or does the even store only holds audit records and actual read entities (when there will be many) aren't reconstructable? Thanks.

**Comment by EduardoPires** [comment]
You can create a kind of replay and recreate your entities executing each event (ordered old > new)
