### ISSUE TITLE
Authorization fails for some policies and passes for others

### ISSUE THREAD

**Issue by coretravis** [EduardoPires/EquinoxProject#152]
Hi,
I'm not sure if anyone else has come across this issue where authorization will fail for certain policies and passes for others even though they are all properly registered.

Turns out the ClaimsRequirementHandler class is responsible and here is why;

`var claim = context.User.Claims.FirstOrDefault(c => c.Type == requirement.ClaimName);
            if (claim != null && claim.Value.Contains(requirement.ClaimValue))
            {
                context.Succeed(requirement);
            }`

It is possible for validation to fail since the FirstOrDefault will return the first matching Claim with the claim name but not necessarily the claim with its value; The update below fixes the issue;

`var claim = context.User.Claims.FirstOrDefault(c => c.Type == requirement.ClaimName && c.Value.Contains(requirement.ClaimValue));

            if (claim != null)
            {
                context.Succeed(requirement);
            }`

Or am i missing something. 
Thanks for sharing this project and also the effort that went into it.

**Comment by EduardoPires** [comment]
Your suggestion seems ok.
