### ISSUE TITLE
New feature request: Update to Net Core 3

### ISSUE THREAD

**Issue by pavini** [EduardoPires/EquinoxProject#153]
Update project to Net Core 3.0

**Comment by ncxn** [comment]
I use this architecture on .net core 3.0 and It work fine!

**Comment by pavini** [comment]
@ncxn What you change on this project to build on 3.0. There is some breaks after the upgrade.

**Comment by ncxn** [comment]
Hello,
It was not possible to upgrade directly to version 3.0, so I upgraded manually. It is not difficult at all. (The code is the same, but some NuGet pack changes).

**Comment by pavini** [comment]
Hi @ncxn ,

I already update the packages, but there are some break changes with the new packages. Can you create a PR with these changes?

**Comment by EduardoPires** [comment]
@pavini @ncxn 

Done. Migrated to 3.1
