### ISSUE TITLE
Separation concerns should not avoid 3rd party frameworks on application layer?

### ISSUE THREAD

**Issue by leandrofagundes** [EduardoPires/EquinoxProject#155]
Hi @EduardoPires,

I was wondering if the application layer could have a dependency to the automapper. After reading a little about architecture (Clean Architecture mainly) I step into the point of the Domain and Application layers never have dependencies of any other framework or libraries.

Can you explain it a little more and if it's ok or not?

Thanks

**Comment by knuxbbs** [comment]
I think that the application layer main purpose is to take the complexity from the presentation layer.
