### ISSUE TITLE
inserting the same Customer several times generates duplicate records

### ISSUE THREAD

**Issue by NecroKorn** [EduardoPires/EquinoxProject#157]
**Describe the bug**
When I make a Curtomer data insertion call servide directly (using the same record, with the same data) with 3 threads that run simultaneously, it creates more than one record with the same data but with different IDs, indicating that I am using the Customer class where the Email is the primary key to validate

is there any way to control this event?

**Comment by EduardoPires** [comment]
Simple solution:

Set e-mail column as Index

**Comment by NecroKorn** [comment]
Thanks a lot,!
