### ISSUE TITLE
Immediate consistency or how to know if Register customer was successful

### ISSUE THREAD

**Issue by maxpavlov** [EduardoPires/EquinoxProject#158]
At the moment, CustomerController in Equinox.Services.Api will always return status 200 to any request to register a new customer since the consistency is not implemented and the error feedback loop from a Register method in CustomerAppService. Basically it will send a command to register a new customer to an in-memory bus, bus will write a generic (not linked to a particular transaction) message to a "notifications" store and that's it, the message will simply stay in that store. Yes, the Handle task will return false instead of a true, but since the repo is intended to teach users a clean architecture, may I ask - is this how it should be? What is the "by the books way" of validating if the "operation is successful" and feedback it to a calling API? Thanks.

**Comment by EduardoPires** [comment]
This project uses imediate consistency and now is returning 204 from API
