### ISSUE TITLE
Identity custom field

### ISSUE THREAD

**Issue by pavini** [EduardoPires/EquinoxProject#159]
Dear,

I'm trying to add a new custom field (FullName) to identity.

```
public class CustomIdentityUser : IdentityUser
    {
        [PersonalData]
        public string FullName { get; set; }
    }

```
My Startup.cs class

```
 public static void AddIdentitySetup(this IServiceCollection services)
        {
            if (services == null) throw new ArgumentNullException(nameof(services));

            services.AddDefaultIdentity<CustomIdentityUser>(options =>
                {
                    options.SignIn.RequireConfirmedAccount = true;
                })
                .AddEntityFrameworkStores<ApplicationDbContext>();
        }
```

ApplicationDbContext.cs

```
public class ApplicationDbContext : IdentityDbContext
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
            : base(options)
        {
        }
    }
```

My update-database do not identify the new field.

**Comment by paulosiquiero** [comment]
You need to specify the CustomIdentityUser in the IdentityDbContext extension.

public class ApplicationDbContext : IdentityDbContext<CustomIdentityUser> { ...

**Comment by paulosiquiero** [comment]
You need to specify the CustomIdentityUser in the IdentityDbContext inheritance.

public class ApplicationDbContext : IdentityDbContext { ...

**Comment by paulosiquiero** [comment]
You need to specify the CustomIdentityUser in the IdentityDbContext inheritance.

public class ApplicationDbContext : IdentityDbContext<CustomIdentityUser> { ...

**Comment by paulosiquiero** [comment]
Tou need to specify the CustomIdentityUser in the ApplicationDbContext inheritance.

`public class ApplicationDbContext : IdentityDbContext<CustomIdentityUser> { ...`
