### ISSUE TITLE
XSS vulnerability

### ISSUE THREAD

**Issue by ipvalverde** [EduardoPires/EquinoxProject#16]
Hi,

The system has a XSS vulnerability in the auditing/history page.
The JSON data received by the ajax request is not being html-encoded.

**Comment by EduardoPires** [comment]
Thanks for reporting!
I'll fix in next version

**Comment by EduardoPires** [comment]
Done.

**Comment by attritionorg** [comment]
@EduardoPires Can you link to the fixing commit please?
