### ISSUE TITLE
Customer "Write" and "Remove" claims are only added with Presentation registration

### ISSUE THREAD

**Issue by maxpavlov** [EduardoPires/EquinoxProject#160]
Both API and MVC (aka Presentation) apps require "Customer" - "Write" and "Remove" claims for Customer management controllers. However, an API "Register" action in an `AccountController` does not add those claims to a user. MVC does. Thus I assume users created through an API will not be able to manipulate customers. Is this an intended logic?

**Comment by EduardoPires** [comment]
You can add the claims manually or create some feature to manage user claims.
