### ISSUE TITLE
Generate Identity related tables

### ISSUE THREAD

**Issue by mayureshs** [EduardoPires/EquinoxProject#166]
Is there a documentation on how to start this project ?  I have ran two update-database commands for the two DbContext in the Infra.Data project. But how do I create the Identity related tables ? They are not getting created upon startup and Registration throws an error.

**Comment by faironsp** [comment]
Também estou com essa dificuldade, como gerar os modelos e como dar um update, add um migration, por favor nos ajude :)

**Comment by carloshenriqueribeiro** [comment]
When did you run update-database, did you set the right project ? Sent the -Context parameter ?

Could you send the commands and result of it ?

For me works fine.

**Comment by mayureshs** [comment]
I had to run the below scripts to create the database. However it was missing the Identity tables. How can I create those ?
dotnet ef database update --context EquinoxContext --project Equinox.Infra.Data/Equinox.Infra.Data.csproj --startup-project Equinox.UI.Web/Equinox.UI.Web.csproj
dotnet ef database update --context EventStoreSqlContext --project Equinox.Infra.Data/Equinox.Infra.Data.csproj --startup-project Equinox.UI.Web/Equinox.UI.Web.csproj

**Comment by TeoDanilo** [comment]
> I had to run the below scripts to create the database. However it was missing the Identity tables. How can I create those ?
> dotnet ef database update --context EquinoxContext --project Equinox.Infra.Data/Equinox.Infra.Data.csproj --startup-project Equinox.UI.Web/Equinox.UI.Web.csproj
> dotnet ef database update --context EventStoreSqlContext --project Equinox.Infra.Data/Equinox.Infra.Data.csproj --startup-project Equinox.UI.Web/Equinox.UI.Web.csproj

There are a third Context to update, the ApplicationDbContext on Equinox.Infra.CrossCutting.Identity

**Comment by mayureshs** [comment]
Thanks for your comment, However I do not see the third context in Equinox.Infra.CrossCutting.Identity

https://github.com/EduardoPires/EquinoxProject/tree/master/src/Equinox.Infra.CrossCutting.Identity

**Comment by TeoDanilo** [comment]
Oh sorry, looks like the version I have here is outdated, Eduardo change it recently to "NetDevPack.Identity".

**Comment by mayureshs** [comment]
Looks like it, let me know what I need to run to generate the Identity tables.

**Comment by TeoDanilo** [comment]
> dotnet ef database update --context NetDevPackAppDbContext --project Equinox.Infra.Data/Equinox.Infra.CrossCutting.Identity.csproj --startup-project Equinox.UI.Web/Equinox.UI.Web.csproj

or

> update-database -context NetDevPackAppDbContext

For more information:
https://github.com/NetDevPack/NetDevPack.Identity

**Comment by faironsp** [comment]
No meu caso eu não estava conseguindo gerar as tabelas AspNetUser... etc, era porque o projeto que tinha feito download não veio com os migrations, então primeiro faça a migrations e depois o update database.

dotnet ef migrations add Initial --context NetDevPackAppDbContext --project Equinox.Infra.CrossCutting.Identity/Equinox.Infra.CrossCutting.Identity.csproj --startup-project Equinox.UI.Web/Equinox.UI.Web.csproj

dotnet ef database update --context EquinoxContext          --project Equinox.Infra.Data/Equinox.Infra.Data.csproj                          --startup-project Equinox.UI.Web/Equinox.UI.Web.csproj
dotnet ef database update --context EventStoreSqlContext --project Equinox.Infra.Data/Equinox.Infra.Data.csproj                          --startup-project Equinox.UI.Web/Equinox.UI.Web.csproj
dotnet ef database update --context NetDevPackAppDbContext    --project Equinox.Infra.CrossCutting.Identity/Equinox.Infra.CrossCutting.Identity.csproj --startup-project Equinox.UI.Web/Equinox.UI.Web.csproj

**Comment by pavini** [comment]
Caros,

Nenhuma das opções funcionou pra mim.

```
dotnet ef migrations add Initial --context NetDevPackAppDbContext --project Equinox.Infra.CrossCutting.Identity/Equinox.Infra.CrossCutting.Identity.csproj
Build started...
Build succeeded.
No DbContext named 'NetDevPackAppDbContext' was found.
```

Alguma luz por favor?

**Comment by TeoDanilo** [comment]
> Caros,
> 
> Nenhuma das opções funcionou pra mim.
> 
> ```
> dotnet ef migrations add Initial --context NetDevPackAppDbContext --project Equinox.Infra.CrossCutting.Identity/Equinox.Infra.CrossCutting.Identity.csproj
> Build started...
> Build succeeded.
> No DbContext named 'NetDevPackAppDbContext' was found.
> ```
> 
> Alguma luz por favor?

Tá usando o PowerShell ou o console do nuget? Se for pelo console, certifique-se de que está com o projeto correto selecionado e execute:

update-database -context NetDevPackAppDbContext

**Comment by pavini** [comment]
> > Caros,
> > Nenhuma das opções funcionou pra mim.
> > ```
> > dotnet ef migrations add Initial --context NetDevPackAppDbContext --project Equinox.Infra.CrossCutting.Identity/Equinox.Infra.CrossCutting.Identity.csproj
> > Build started...
> > Build succeeded.
> > No DbContext named 'NetDevPackAppDbContext' was found.
> > ```
> > 
> > 
> > Alguma luz por favor?
> 
> Tá usando o PowerShell ou o console do nuget? Se for pelo console, certifique-se de que está com o projeto correto selecionado e execute:
> 
> update-database -context NetDevPackAppDbContext

TeoDanilo, eu estou usando o terminal do MacOS

**Comment by TeoDanilo** [comment]
> > > Caros,
> > > Nenhuma das opções funcionou pra mim.
> > > ```
> > > dotnet ef migrations add Initial --context NetDevPackAppDbContext --project Equinox.Infra.CrossCutting.Identity/Equinox.Infra.CrossCutting.Identity.csproj
> > > Build started...
> > > Build succeeded.
> > > No DbContext named 'NetDevPackAppDbContext' was found.
> > > ```
> > > 
> > > 
> > > Alguma luz por favor?
> > 
> > 
> > Tá usando o PowerShell ou o console do nuget? Se for pelo console, certifique-se de que está com o projeto correto selecionado e execute:
> > update-database -context NetDevPackAppDbContext
> 
> TeoDanilo, eu estou usando o terminal do MacOS

Sorry for the long time, did you menage to resolve this? If not, or if someone else have this issue, try do add migration to the Identity project.
