### ISSUE TITLE
 Configuração padrão do Identity no NetDevPack.Identity

### ISSUE THREAD

**Issue by jpdelboni** [EduardoPires/EquinoxProject#169]
Existe uma forma de quando usar o comando do NetDevPack - AddIdentityConfiguration customizar os tipos do IdentiyUser e IdentityRole?
Assim que o comando AddIdentityConfiguration ele registra essas classes como string, gostaria de usar o Guid.

**Comment by EduardoPires** [comment]
English please. This is a 'global' project
