### ISSUE TITLE
Some services are not able to be constructed (Error while validating the service descriptor)

### ISSUE THREAD

**Issue by pranavpatil19** [EduardoPires/EquinoxProject#176]
Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: NetDevPack.Mediator.IMediatorHandler Lifetime: Scoped ImplementationType: EventBus.Memory.InMemoryBus': Unable to resolve service for type 'Domain.Core.Events.IEventStore' while attempting to activate 'EventBus.Memory.InMemoryBus'.)'

**Comment by TeoDanilo** [comment]
You are trying to execute the Project with or without alterations?

**Comment by EduardoPires** [comment]
@pranavpatil19 the original code is working.
