### ISSUE TITLE
Essa arquitetura CQRS + ES ainda é considerada válida?

### ISSUE THREAD

**Issue by eliezeralmeida** [EduardoPires/EquinoxProject#177]
Estou iniciando um projeto webapi com arquitetura CQRS e encontrei o Equinox, alguém que utiliza e tem mais conhecimento no assunto poderia dizer se essa ainda é um arquitetura válida para uso?

**Comment by FernandoVezzali** [comment]
Olá Elieze, tudo bem? Com certeza é valida.

Acho que a pergunta que você deveria se fazer é a arquitetura encaixa com a sua necessidade.

**Comment by eliezeralmeida** [comment]
Aparentemente se encaixa perfeitamente no que eu quero fazer, estava na dúvida se iria precisar dos registros de eventos, ai cheguei na conclusão que será muito compensador ter estes eventos registrados quando algum comando alterar o estado de algo permanentemente no banco de dados.

Em algumas pesquisas identifiquei que o padrão Event Sourcing é utilizado para substituir a alteração de registros no banco de dados, onde ao invés de inserir um registro e depois altera-lo futuramente, podemos optar por utilizar o padrão ES e sempre persistir o estado atual da entidade.

**Nesse exemplo da Equinox percebi que existe a entidade como é comum no banco de dados, onde ela sofre alterações ou exclusões, porém existe um lugar específico só para armazenar os eventos, que achei interessante por tirar a complexidade do event source usado da forma como vi.**

Essa abordagem de usar um banco com registros mutáveis e armazenar os eventos em outro lugar é considerada boa na sua opinião @FernandoVezzali ?

**Comment by rafaelfgx** [comment]
@eliezeralmeida, como o @FernandoVezzali falou anteriormente sobre o projeto ser válido, nesse caso a pergunta que você deveria se fazer não é "se armazenar os eventos em outro lugar é considerada boa", mas sim se o Event Sourcing é uma boa para o seu contexto.

Event Sourcing é um padrão muito bom, MAS é trabalhoso de aplicar na prática, e por isso só se justifica nos cenários em que realmente é necessário.

É necessário estudar e entender muito bem sobre o assunto, então você saberá se encaixa para o seu contexto ou não. É dessa forma que como desenvolvedores e arquitetos devemos evitar "Overengineering".

Espero ter ajudado a sanar dúvidas, fique à vontade para perguntar e compartilhar.

**Comment by eliezeralmeida** [comment]
@rafaelfgx obrigado por responder, o Event Sourcing é um ótimo recurso para meu contexto, estava na dúvida sobre seu armazenamento separado, diferente do que eu havia pesquisado. Porém presumo que o mesmo foi implementado dessa maneira para ser usado em um banco de dados NO SQL, já que utiliza apenas uma tabela e armazena os dados como JSON. 

Agradeço a todos pelo apoio.
