### ISSUE TITLE
Need migration commands to start with the projects

### ISSUE THREAD

**Issue by shubhamdhanetia** [EduardoPires/EquinoxProject#178]
I created a database Equinox in SQL Server and updated the connection string in the appsettings.json file to 

"DefaultConnection": "Server=localhost; Database=Equinox; Trusted_Connection=True; Persist Security Info=True;Connect Timeout=30"

Run the migration commands on two Context objects on the project Infra.Data

Add-Migration InitialMigration -c EquinoxContext
Add-Migration InitialMigration -c EventStoreSQLContext

Update-Database -c EquinoxContext
Update-Database -c EventStoreSQLContext

Those commands are properly executed. But when I open the database in SQLServer, I see no tables.

Am I missing something ?

**Comment by EduardoPires** [comment]
If the update command was executed with success the tables need to be there. Did you checked the correct DB?
