### ISSUE TITLE
Ajuda para teste Teste de unidade para o CommandHandler e assert do evento publicado

### ISSUE THREAD

**Issue by eliezeralmeida** [EduardoPires/EquinoxProject#182]
### Cenário

Utilizei alguns conceitos da arquitetura do projeto Equinox, um dos recursos foi o de publicar eventos pelo mediator utilizando a mesma técnica do projeto, onde tem um método commit na DbContext e esse método é o responsável por publicar os eventos que estão na Entidade.

## O que estou testando

Estou testando um command handler, no caso que irei apresentar é o ClienteHandler manipulando o NovoClienteCommand, quero nesse teste checar se se o MediatR.Publish foi chamado uma única vez, pq considero uma regra muito importante do meu  domínio garantir que esse evento tenha sido criado (não sei se faz sentido essa analogia).

## Exemplo de código

![image](https://user-images.githubusercontent.com/2786448/118990901-a8ca7300-b959-11eb-8d4d-c85655154d8f.png)

## Problema que identifiquei

Pelo fato da implementação do DbContext ser responsável por fazer essa chamada e o Moq injeta um Mock de Repository, e logo o publish não é chamado. 

Não estou conseguindo testar esse fato. 
Alguém possui alguma dica para me ajudar e que possa compartilhar?

**Comment by EduardoPires** [comment]
I'm closing this issue. To be more inclusive with the global community we are just accepting issues in English.
