### ISSUE TITLE
implement business rules involving multiple entities

### ISSUE THREAD

**Issue by NecroKorn** [EduardoPires/EquinoxProject#184]
To implement domain services, do I necessarily need to execute sendCommand? 

Is it possible to create a service as an orchestrator that performs a process by executing actions on more than one entity in the same domain?

**Comment by EduardoPires** [comment]
This project is using CQRS concepts, that decouple the responsibilities of each intention.
You will need a domain service with a cross-aggregate scenario (eg checkoutService) when you have the entities (Product, Order, OrderDetail, Customer, Payment [and more]) in this case there's no only one entity to be responsible, so you need use a domain service to coordinate this kind of complex process.
