### ISSUE TITLE
When updating Identity Migration in the Equinox.UI.Web layer an error is appearing that the object of type ApplicationDbContext cannot be created

### ISSUE THREAD

**Issue by jalberromano1980** [EduardoPires/EquinoxProject#185]
I'm having problems updating Identity Migration on Equinox.UI.Web layer. An error appears stating that it is not possible to create the object of type ApplicationDbContext.

What is wrong?

Console error:

PM> Update-Database -Context: ApplicationDbContext
Build started...
Build succeeded.
Unable to create an object of type 'ApplicationDbContext'. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728
PM>

**Comment by mysharp** [comment]
> I'm having problems updating Identity Migration on Equinox.UI.Web layer. An error appears stating that it is not possible to create the object of type ApplicationDbContext.
> 
> What is wrong?
> 
> Console error:
> 
> PM> Update-Database -Context: ApplicationDbContext
> Build started...
> Build succeeded.
> Unable to create an object of type 'ApplicationDbContext'. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728
> PM>

hi, @jalberromano1980 
     you can add the ApplicationDbContext in the Equinox.UI.Web.Configurations.DatabaseConfig, just like the EquinoxContext. then you can call this: Update-Database -Context: ApplicationDbContext
![image](https://user-images.githubusercontent.com/26587307/132197618-7e3012a5-2432-4987-84f8-3fd38cf2a60e.png)

**Comment by mcojocaru-isn** [comment]
I think you would need to add Microsoft.EntityFrameworkCore.Design if not already and the Equinox.UI.Web must be the default project when doing the update-database

**Comment by ascariz** [comment]
Hi there.
I get the same error when updating the users model.

I have added the dll Microsoft.EntityFrameworkCore.Design (5.0.5).
I select the UI.Web project and the command "add-migration UserEmpleado -context ApplicationDbContext -outputdir Migrations /" and it gives me the same error

What can be?

**Comment by jalberromano** [comment]
I changed some things in the project, but found a solution by doing a lot of testing.
In the "AddDatabaseConfiguration" class I commented:

` //services.AddDbContext<ERPContext>(options =>
            //    options.UseNpgsql(configuration.GetConnectionString("DefaultConnection")));`

And in the DATA layer, in the EquinoxContext class, I created an "OnConfiguring" method:

` protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            // get the configuration from the app settings
            var config = new ConfigurationBuilder()
                .SetBasePath(Directory.GetCurrentDirectory())
                .AddJsonFile("appsettings.json")
                .Build();

            // define the database to use
            optionsBuilder.UseNpgsql(config.GetConnectionString("DefaultConnection"));
            optionsBuilder.EnableSensitiveDataLogging();
        }`

Maybe it's not right, but it worked!

**Comment by ascariz** [comment]
Thanks.

I have commented the code in Equinox.UI.Web.Configurations

```
public static void AddDatabaseConfiguration(this IServiceCollection services, IConfiguration configuration)
        {
            if (services == null) throw new ArgumentNullException(nameof(services));

            //services.AddDbContext<MyRicohCVContext>(options =>
            //    options.UseSqlServer(configuration.GetConnectionString("DefaultConnection")));

            services.AddDbContext<EventStoreSqlContext>(options =>
                options.UseSqlServer(configuration.GetConnectionString("DefaultConnection")));
        }
```

I have changed it but it fails me.


I have added in the project -> Equinox.Infra.Data.Context -> the method -> OnConfiguring but it gives me error here (UseNpgsql), it does not recognize it.

optionsBuilder.UseNpgsql(config.GetConnectionString("DefaultConnection"));

I don't know how to fix it. some way?

**Comment by jalberromano** [comment]
When creating the protected override method void OnConfiguring (DbContextOptionsBuilder optionsBuilder) everything worked correctly for my case.

**Comment by EduardoPires** [comment]
Hi @jalberromano @jalberromano1980 is the same person? Can I consider this issue closed?

**Comment by ascariz** [comment]
I have changed the line ->
optionsBuilder.UseNpgsql (config.GetConnectionString ("DefaultConnection"));
by
optionsBuilder.UseSqlServer (config.GetConnectionString ("DefaultConnection"));
but it keeps giving me this error.?
Unable to create an object of type 'ApplicationDbContext'. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728
any solution?.

**Comment by EduardoPires** [comment]
@ascariz changing the provider don't change the necessary configuration to make your context works.

You need to check if your context setup are correct
