### ISSUE TITLE
Relate in EquinoxContext AspNetUsers with Employee

### ISSUE THREAD

**Issue by ascariz** [EduardoPires/EquinoxProject#186]
Hello good
I loved the project, sorry for my English

But I have to join the AspNetUsers table to an employee table, but I don't know how to do it, I'm doing it like this, but I don't know how to do it in E.F.

I have to create the AspNetUsers table in the Domain.Models and add a field that is Employee Id, or how I have to do it.
any ideas?
thank you.

**Comment by EduardoPires** [comment]
Hi!

The AspNetUsers is for user control. If you need add more details to this "persona" that's represented by the user I recommend to have a new table "Employees" and share the same PK as you have in the AspNetUsers
