### ISSUE TITLE
Where to put WEB API?

### ISSUE THREAD

**Issue by levalencia** [EduardoPires/EquinoxProject#19]
In my next project I would like to use this as an starting point, however we also need to create a REST API to expose system functionality, where would this project fit in the entire architecture?

**Comment by CodeWorldIndustries** [comment]
have you tried just creating a new project? WebAPI then either create a new folder called Api and create your controllers that inherit from ApiController. From there each request would start from the bus, make its way to the command, command handler, domain, event, event handler... etc.

Example: 
`
        public ICommandBus CommandBus;

        public MovieController() : this(ServiceLocator.Current.Resolve<ICommandBus>())
        {

        }

        public MovieController(ICommandBus commandBus)
        {
            CommandBus = commandBus;
        }

        [HttpGet]
        public HttpResponseMessage Get()
        {
            return Request.CreateResponse(HttpStatusCode.OK, "worked!");

        }

        [HttpGet]
        public HttpResponseMessage GetById(Guid id)
        {
            return Request.CreateResponse(HttpStatusCode.OK, "worked!");
        }

        [HttpPost]
        public HttpResponseMessage Post(CreateMovieCommand command)
        {
            var createMovieCommand = CommandBus.Execute(command);
            return Request.CreateResponse(HttpStatusCode.OK, "worked!");

        }

        [HttpPut]
        public HttpResponseMessage Put(UpdateMovieCommand command)
        {
            CommandBus.Execute(command);
            return Request.CreateResponse(HttpStatusCode.OK, "worked!");
        }
    }
}`
