### ISSUE TITLE
Update DataBase

### ISSUE THREAD

**Issue by ascariz** [EduardoPires/EquinoxProject#199]
Hello.
Thanks for this project and sorry for my English.
I have changed all connections to DB

I am trying to update the DB, I have modified sql server and in VS PowerShell I select the Equinox.Infra.Data project and execute these commands but it does nothing.

add-migration ProjectsPart1 -context EquinoxContext -outputdir Migrations/

What can be?

**Comment by JohnSalazar** [comment]
Hello Rodrigo Ascariz, after creating the migration with the add-migration
command, you need to apply the migration through the update-database
-context EquinoxContext command

Em ter., 5 de dez. de 2023 07:47, Rodrigo Ascariz ***@***.***>
escreveu:

**Comment by ascariz** [comment]
The problem is that the file created by the add-migration command is created empty, not with the new tables that I have in SQL Server

**Comment by ascariz** [comment]
Good morning.
Sorry for the English.
I have done it several times, change the files
Equinox.Infra.Data -> appsettings.json
Equinox.Services.Api -> appsettings.json
Equinox.UI.Web -> appsettings.json

But I am unable to update the Database, I have created the entities in the Domain.Models project and also in the Database. I execute the commands
add-migration ProjectsLetters -context EquinoxContext
update-database -context EquinoxContext

and it creates the empty ProyectosCartas.cs file.

What can happen?

**Comment by ascariz** [comment]
Solved, thank you
