### ISSUE TITLE
Add a components diagram

### ISSUE THREAD

**Issue by xperiandri** [EduardoPires/EquinoxProject#20]
Could you add a components diagram like layer diagram or so.
It will help to understand relations and whole architecture.

**Comment by thiagolunardi** [comment]
You could use this as a reference.

![DDD](http://3.bp.blogspot.com/-cuFTNVOsPoA/VM-uTHdlitI/AAAAAAAAARA/jDb1zInYQ_Y/s1600/ddd-nlayered.jpg "DDD")

**Comment by EduardoPires** [comment]
The diagram above is near of the real implementation, but I'm using CQRS pattern instead domain services. The advantage is split the read and write responsibilities.
