### ISSUE TITLE
How to use SelectListItem for dropdown

### ISSUE THREAD

**Issue by MKI-Miro** [EduardoPires/EquinoxProject#21]
Hi

I need to use dropdown. So for example i need to add this 
`public IEnumerable<SelectListItem> CreditCards { get; set; `
to
`CustomerViewModel`
but SelectListItem is part of Microsoft.AspNetCore.Mvc.ViewFeatures.dll

Is it correct to add MVC dependency to Application project?

Thanks

**Comment by thiagolunardi** [comment]
Hi @MKI-Miro 

> Is it correct to add MVC dependency to Application project?

God no! You Application should not be aware of what kind of client is consuming it - web, mobile, windows, don't care. So, no dependency at all on it. The Application project should be ready to serve any kind of project.

About the `SelectListItem`...

Actually, this depends on you. You can extend the `CustomerViewModel` class in you presentation layer and add more properties to it.

You also can - but shouldn't - create the `SelectListItem` directly at your Razor view.

**Comment by MKI-Miro** [comment]
but I cannot add SelectListItem to CustomerViewModel.... (because of dependency to MVC)

so what is the solution?

**Comment by thiagolunardi** [comment]
You extend it.

At you UI.Web project, create a file `/CustomViewModels/MyCustomerViewModel.cs`

```
public class MyCustomerViewModel : CustomerViewModel
{
    public IEnumerable<SelectListItem> CrediCards { get; set; }
}
```

**Comment by MKI-Miro** [comment]
but CustomerAppService does not reference UI.Web

**Comment by thiagolunardi** [comment]
Yes, it does. 
The UI.Web project do reference mainly to Application project.

**Comment by thiagolunardi** [comment]
Ok, we are missing some info here.

What you have right now at your `Application.ViewModels.CustomerViewModel`?

Can you share the code here?

**Comment by MKI-Miro** [comment]
nothing :) it was just wondering how to do it. All I have is your code. So maybe you can extend your application with one dropdown.

**Comment by thiagolunardi** [comment]
But I already show you that with `MyCustomerViewModel` sample.

What you didn't get it?

**Comment by thiagolunardi** [comment]
Can we close your issue, @MKI-Miro ?

**Comment by EduardoPires** [comment]
I think @thiagolunardi helped you, if you have more questions please reopen the issue.
