### ISSUE TITLE
Suggestions for unit tests [discussion]

### ISSUE THREAD

**Issue by khaueviana** [EduardoPires/EquinoxProject#25]
Hey folks,

I'm beginning the unit tests in this project. 

What are your suggestions for the frameworks?

My suggestions are XUnit and NSubstitute.

**Comment by thiagolunardi** [comment]
Take a look here: [https://github.com/EduardoPires/UnitTestingTools](https://github.com/EduardoPires/UnitTestingTools).

**Comment by khaueviana** [comment]
Ok. 
I'll look at this and use it!

**Comment by khaueviana** [comment]
@EduardoPires is ok for you?

**Comment by EduardoPires** [comment]
Yes! I recommend the tools collection in this project. In the future I will implement all this stuff in Equinox...

**Comment by khaueviana** [comment]
I Will implement ;)
