### ISSUE TITLE
Run weapi and and site

### ISSUE THREAD

**Issue by digounet** [EduardoPires/EquinoxProject#26]
Hello,

How can I run both weapi and and site ?

If I go to the webapi folder and run the dotnet run command, I can't access the site URL. The same if I run dotnet run in the site folder..

Thanks.

**Comment by EduardoPires** [comment]
You need to run in two separated process.
Try running with this command, user different port for each project:

SET ASPNETCORE_URLS=https://*:5123 && dotnet run

**Comment by digounet** [comment]
Thank you Eduardo. I will try it. Another little question: to authenticate a mobile app one the webapi, have I to implement JWT or can I use it as is? Thanks

**Comment by EduardoPires** [comment]
@digounet The best solution is using a token!
