### ISSUE TITLE
Go further and implements IdentityServer4

### ISSUE THREAD

**Issue by thiagolunardi** [EduardoPires/EquinoxProject#29]
Implements a further segregation of Identity service and use [IdentityServer4](https://github.com/IdentityServer/IdentityServer4) and full isolate it as running service.

**Comment by davesunny1985** [comment]
hi there,

How can I have async Controllers in the project?
It would be great if you have guide me on that. And also do I need to use MQ or MediatR etc. for Async operation?

Please let me know

Thanks & Regards,
Sunny Dave

**Comment by thiagolunardi** [comment]
@davesunny1985 , please, create a new issue with you question, buddy.

**Comment by kanpinar** [comment]
Isolating Identity Server and Using Web Api kind another project has pros and cons
I am using this project and aproach becouse ; its KISS 

I mentioned ASP.NET Boiler Plate and Zero its very well designed but too complex and 
hard to work with...

Please Keep it Simple or Give chance to people for keeping it simple wich work with small team (maybe only 1 person)

Thanks and Reagards
Mehmet Kanpinar

**Comment by thiagolunardi** [comment]
About WebAPI: The idea is to give a sample of how to use all Equinox approach for ones that want to avoid using MVC - I'm this kind, always using SPA + API solution.

About IdServer: That's a God's feeling the direction is going. Full responsibility segregation. Your business should try to avoid to know what a `User` is. Instead, the business knows what a `Customer` is. Also, my app should not be responsible for identification, the idea behind is, anyone using the app is already a known and identified person.

Take a look what's coming with netcore 2.0. They are really pushing to this direction. Nonetheless, nothing stops you to setup on same web project, your app and the IdServer settings - after IdServer is migrated to netcore 2.0, ofc. ;)

**Comment by kanpinar** [comment]
Is there any date for V3 ?

**Comment by EduardoPires** [comment]
We are using NetDevPack.Identity that works well, IDS 4 is not necessary and now is a paid service.
