### ISSUE TITLE
Entity Relations.

### ISSUE THREAD

**Issue by AliCharper** [EduardoPires/EquinoxProject#31]
Can you please add a complicated MODEL and show how can we implement ONE-Many and Many-Many relations also?.

**Comment by AliCharper** [comment]
Just having the Customer table can not solve the problem. Please add more Entities and teach us how to use them together. Thanks.

**Comment by thiagolunardi** [comment]
Hey @AliCharper , what problem are you trying to solve?

One-To-Many and Many-To-Many concerns are persistency concerns.
As we are using EntityFramework as ORM for our persistency layer, you can just map them like through this.

```
// one-to-many 
modelBuilder.Entity<Student>()
    .HasRequired<Course>(s => s.Course)
    .WithMany(s => s.Students)
    .HasForeignKey(s => s.CourseId);
```

```
// many-to-many
modelBuilder.Entity<Student>()
    .HasMany<Course>(s => s.Courses)
    .WithMany(c => c.Students)
    .Map(cs =>
    {
        cs.MapLeftKey("StudentId");
        cs.MapRightKey("CourseId");
        cs.ToTable("StudentCourse");
    });
```

**Comment by AliCharper** [comment]
Yes. Thanks, but then we have to use Automapper, define ViewModel and new event. I wish I had a sample a bit more complicated. I mean with a more complex model only.

**Comment by AliCharper** [comment]
I am talking the whole concept. I am a bit lost in defining Events and ... when I have a complex Model(DB).

**Comment by EduardoPires** [comment]
You can research about more complicated scenarios using AutoMapper and EF.

In the v2.0 I will implementing some cases like that!
