### ISSUE TITLE
Unique customer name validation

### ISSUE THREAD

**Issue by achmstein** [EduardoPires/EquinoxProject#33]
How can I handle the validation of a unique customer name?

**Comment by thiagolunardi** [comment]
During the handling of `RegisterNewCustomerCommand`, you can ask the `_customerRepository` if already exist any record with that same name.

To simplify, the same way that it's [been doing with the email validation](https://github.com/EduardoPires/EquinoxProject/blob/master/src/Equinox.Domain/CommandHandlers/CustomerCommandHandler.cs#L39).

```
   if (_customerRepository.GetByEmail(customer.Email) != null)
            {
                Bus.RaiseEvent(new DomainNotification(message.MessageType, "The customer e-mail has already been taken."));
                return;
            }
```

But you may change for do the same with names.

**Comment by achmstein** [comment]
I think that we should validate name/email uniqueness in "CustomerValidation". am I right?

**Comment by EduardoPires** [comment]
@achmstein Not in this case. The customer validation is about consistency of the fields data. Not about uniqueness. 

If you want check if is unique you can do it in the Handler and/or encapsulate this verification in an isolated method for code reuse.
