### ISSUE TITLE
Pull request

### ISSUE THREAD

**Issue by digounet** [EduardoPires/EquinoxProject#34]
Hello Eduardo,

I've implemented JWT access token in WebApi project. I'm trying to send a pull request to your branch  but I haven't authorization.

**Comment by EduardoPires** [comment]
It's nice!

But in this case keep this changes for you because we are working in v2 with an special implementation of JWT.

Thank you!

**Comment by m2017atTR** [comment]
Hello,
for V2 is there a time to publish or open source?
