### ISSUE TITLE
Project - Documentation??

### ISSUE THREAD

**Issue by satishbyali** [EduardoPires/EquinoxProject#35]
Hi, 
This is a great project for me to learn and contribute.
I have cloned and running it to test.

Is there a document or e-book available for better understanding the details?

Thanks.

**Comment by thiagolunardi** [comment]
[<img src="https://images-na.ssl-images-amazon.com/images/P/B00794TAUG.01.L.jpg">](https://lesen.amazon.de/kp/embed?asin=B00794TAUG&preview=newtab&linkCode=kpe&ref_=cm_sw_r_kb_dp_S-7OzbE9123AB&tag=thiagolunardi-21)

[<img src="https://images-na.ssl-images-amazon.com/images/P/B00BCLEBN8.01.L.jpg">](https://lesen.amazon.de/kp/embed?asin=B00BCLEBN8&preview=newtab&linkCode=kpe&ref_=cm_sw_r_kb_dp_X-7OzbAB45SRB&tag=thiagolunardi-21)

[<img src="https://images-na.ssl-images-amazon.com/images/P/B008OHVDFM.01.L.jpg">](https://lesen.amazon.de/kp/embed?asin=B008OHVDFM&preview=newtab&linkCode=kpe&ref_=cm_sw_r_kb_dp_8-7Ozb82XPKP6&tag=thiagolunardi-21)
