### ISSUE TITLE
Problème dans la modification d'un objet par exemple Customer

### ISSUE THREAD

**Issue by houssam-saissi** [EduardoPires/EquinoxProject#36]
Bonjour,

Nous ajoutons une colonne "Adresse" à l'entité "Customer". Lors de l'insertion d'une nouvelle ligne, nous affectons la valeur : "Mon-Adresse" à la propriété "Adresse". Maintenant si nous souhaitons modifier toutes les colonnes de l'entité "Customer" sauf "Adresse", cette dernière se retrouve avec <chaine vide> dans la base de données  : son ancienne valeur a été écrasée.

Merci

**Comment by thiagolunardi** [comment]
@houssam-saissi Please, address your message in english.

**Comment by houssam-saissi** [comment]
We add an "Address" column to the "Customer" entity. When inserting a new line, we assign the value: "My-Address" to the "Address" property. Now if we want to change all the columns of the "Customer" entity except "Address", the latter will be found in the database: its old value has been overwritten.

**Comment by houssam-saissi** [comment]
Hi
How do you change only the Name of a Customer for example without edited other properties?

**Comment by thiagolunardi** [comment]
One option is, at [CustomerCommandHandler](https://github.com/EduardoPires/EquinoxProject/blob/master/src/Equinox.Domain/CommandHandlers/CustomerCommandHandler.cs), add a new Handler - ofc, create a new `UpdateCustomerNameCommand`

```
        public void Handle(UpdateCustomerNameCommand message)
        {
            // validations

            var customer =  _customerRepository.GetById(customer.Id);
            customer.Name = message.Name;
            _customerRepository.Update(customer);

            // commits and events
        }
```

**Comment by houssam-saissi** [comment]
Thansk for reply :),

But this is not a good method because if I have 100 properties in my Customer class I will need 100 Handler in this case !!

And then if I have a form with 10 fields and if I have modified only 1 field, the others must not be modified (only the modified field that must be saved!)

Additionally, "customer.Name" is a private property that can not be accessed. And if I create a function to do so I have to create for each property a similar function which is not practical!

Any solutions :/ ?

**Comment by thiagolunardi** [comment]
That's a different question, I replied about "How do you change only the Name of a Customer for example without edited other properties".  You could in same direction, you just should stop to think about it for a few minutes:

   public void Handle(UpdateCustomerDataCommand message)
        {
            // validations

            var customer =  _customerRepository.GetById(customer.Id);
            customer.Name = message.Name;
            customer.Prop1 = message.Prop1;
            customer.Prop2 = message.Prop2;
            customer.Prop3 = message.Prop3;
            // ...

            _customerRepository.Update(customer);

            // commits and events
        }


@EduardoPires , you may close this issue.

**Comment by houssam-saissi** [comment]
This is not a solution to my problem. The UPDATE function must be generic to modify only the properties that exist in ModelView because in advance it is not known exactly which property will be modified. It must be generic !!

**Comment by thiagolunardi** [comment]
I'm sorry, this support is not meant to support anyone to do their own work/job.
If you have any question about the Equinox project, about what is actually written and published, or find a bug or to suggest any improvements, you are welcome.

**Comment by EduardoPires** [comment]
What you can do is send the entire model to the Handler, recover the original from DB and only set the Fields that you want to accept changes.

So when you save the changes you will keep the others fields that you won't change
