### ISSUE TITLE
Not to having GUID as primary key for all the tables

### ISSUE THREAD

**Issue by AliCharper** [EduardoPires/EquinoxProject#37]
Hi,

My existing database does not have a GUID as primary key for all the tables. What should I do now?.

**Comment by thiagolunardi** [comment]
Can you provide more info about your database? 
Are you trying just to run Equinox at your environment, or it's something else?

**Comment by AliCharper** [comment]
I have an existing very complicated DB. That's why I already asked a more complicated sample with more than one Entity which it should have one-one and one-many relation as well.

**Comment by thiagolunardi** [comment]
Ok, let me see how I can help.
You don't need to use Guid as Id, it's not an obligation.
You just need to map the entity properly at your Data Context project.

Asking for a more complex sample is too generic and it will not happen, it's not planned.
But, if you share one small piece of problem at time, we may try to help.

**Comment by AliCharper** [comment]
YES. Thanks. I get lost when I have to monitor events for a complex scenario. I wish it had more than one Model class and handled relations as a sample.

**Comment by thiagolunardi** [comment]
Can you write a small sample snipped  here? Then we can go deep on it.

**Comment by AliCharper** [comment]
1- Some tables do not have GUID as Primary-key and it is integer for example.
2- Entities have relation so I am not sure about how to define a new Event handler for the other Entity.

I did change the AggreatorID from GUID to string and work fine , but I do not know what to do if my table does not have a GUID primary key.

**Comment by AliCharper** [comment]
If I use anything other than GUID as a primarykey, then how to assign to the aggrigatorID ?
--
   public Persons(Guid id, string name, string family, string address)
        {
            Id = id;
            Name = name;
            Family = family;
            Address = address;
        }

the type would be different then.

**Comment by thiagolunardi** [comment]
It's important that you may use one EventSource entity per Domain entity.
So, if the domain entity has Guid Id, the AggrigatorId will be Guid, is it's `int`, so both should be `int`.

**Comment by AliCharper** [comment]
but I do inherit from Entity which has a GUID ID in the base class.

**Comment by thiagolunardi** [comment]
Just remove te Guid Id property from Entity class, and bring it to each Entity specific class.
Your are adjusting, so, ofc, you need to do a few dirty job me make it work.

**Comment by AliCharper** [comment]
so if the primarykey name was not ID and it was not GUID, the aggregateid would not work.Correct?.

**Comment by thiagolunardi** [comment]
The idea behind the aggregateId is just to keep track on changes through eventsourcing. Just create a Guid.New for it and you will be fine. 

They don't need to be the same, just need to have one aggregateid per one Entity.

Imagine if you have compose key for an entity, you don't create a compose aggregateid , just keep one-to-one relation.

**Comment by thiagolunardi** [comment]
@AliCharper May we close this discussion?

**Comment by AliCharper** [comment]
I think so, but I have so many other questions which I would ask later.

**Comment by EduardoPires** [comment]
If you have an Int key for your tables just change it to Int in this sample.
If you have N kinds of keys you can try using a generic datatype passing by the repository configuration like:

public class Repository<TKey, TEntity>

And set your datatype keys as you like.

**Comment by AliCharper** [comment]
Imagine if you have compose key for an entity, you don't create a compose aggregateid , just keep one-to-one relation.

Yes, but imagine that I have an existing DB which has so many tables with IN primarykeys or Composite ones. then how can I assign a GUID as an aggregateId ?.
