### ISSUE TITLE
Automapper : ignore non-existing properties

### ISSUE THREAD

**Issue by houssam-saissi** [EduardoPires/EquinoxProject#38]
Hi, 
How to ignore all destination members, except the ones that are mapped? I tested all the solutions of the forums but it does not work !
Thanks

**Comment by thiagolunardi** [comment]
I'm sorry, what you mean by "destination members"?

**Comment by thiagolunardi** [comment]
I guess this is a [AutoMapper](https://github.com/AutoMapper/AutoMapper/wiki/Getting-started), not related to this project.

**Comment by houssam-saissi** [comment]
OK. another question : 

When I add AutoMapperConfig.RegisterMappings (); In NativeInjectorBootStrapper, the mapping works but when I remove it I get the error: missing type mapping for Customer to .....

Why ?

**Comment by thiagolunardi** [comment]
Again, another ask about AutoMapper using.

I guess this [link](http://lmgtfy.com/?q=automapper+%20missing+type+mapping) can help you.  :)

**Comment by EduardoPires** [comment]
The AutoMapper requires a classic setup to work properly in ASPNET Core.
If you follow the example in this project you will get the desired result.

The AutoMapper will map all equal fields found in the "from / to" classes
