### ISSUE TITLE
Commit on Domain Layers

### ISSUE THREAD

**Issue by jedielson** [EduardoPires/EquinoxProject#4]
Hi Eduardo.

I have read in some article that the application layer is the layer responsible for controlling the transactions carried out by the application.

However, in this project the transactions are being commited in Command handlers.

Of course, it would be quiet to inject an IUnityOfWork implementation into the application services, but with that, we would lose the benefit of launching domain events after the commit is completed, from the domain.

It would be kind of weird, like ... Let's launch a domain event, starting from the application layer. O.0

So I'm in a dilemma.
Can I commit the transaction from the domain, or should we improve the design? And besides, how to improve the design?

Thanks for listening!

**Comment by EduardoPires** [comment]
There is no problem raising events from application layer, it's a business layer too.

But it's a different approach using the CQRS concerns and segregating the read / write way.
There is no exact rule for follow, this is a very known standard, feel free to use in this way without caring about design flaws.

I think that's not necessary to think about design improvements, do you have some suggestion?

**Comment by jedielson** [comment]
Thanks for your attention!

So if I want to use my UnityOfWork in the Application Service it would be ok, right!
It would be the only change I would propose.
