### ISSUE TITLE
Visual Studio Issue

### ISSUE THREAD

**Issue by kanpinar** [EduardoPires/EquinoxProject#42]
I have a problem with visual studio 2017 15.3.3 version.
I am trying to use core 2.0 version of this project. clonned and 

if i run with F5 then works well, dotnet run works well,
but if i use right click wwwroot and select Wiev In Browser kestrel gives some error that  i could not solve.

Equinox.UI.Site> Now listening on: http://localhost:18888
Equinox.UI.Site> Application started. Press Ctrl+C to shut down.
Equinox.UI.Site> info: Microsoft.AspNetCore.Server.Kestrel[17]
Equinox.UI.Site>       Connection id "0HL7PLV6P81VF" bad request data: "Malformed request: invalid headers."
Equinox.UI.Site> Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Malformed request: invalid headers.
Equinox.UI.Site>    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
Equinox.UI.Site> info: Microsoft.AspNetCore.Server.Kestrel[17]
Equinox.UI.Site>       Connection id "0HL7PLV6P81VF" bad request data: "Malformed request: invalid headers."
Equinox.UI.Site> Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Malformed request: invalid headers.
Equinox.UI.Site>    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
Equinox.UI.Site> info: Microsoft.AspNetCore.Server.Kestrel[17]
Equinox.UI.Site>       Connection id "0HL7PLV6P81VG" bad request data: "Malformed request: invalid headers."
Equinox.UI.Site> Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Malformed request: invalid headers.
Equinox.UI.Site>    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
Equinox.UI.Site> info: Microsoft.AspNetCore.Server.Kestrel[17]
Equinox.UI.Site>       Connection id "0HL7PLV6P81VG" bad request data: "Malformed request: invalid headers."
Equinox.UI.Site> Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Malformed request: invalid headers.
Equinox.UI.Site>    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()

**Comment by mateushortenciodossantos** [comment]
Hi, have you solved this problem? I'm facing a very similar issue, and I don't know where it is coming from.
Mine happens when it's a nonlocal env, started suddenly

**Comment by pavelgronsky** [comment]
Update your library version in your package.json. It's help for me!

**Comment by vip8668** [comment]
> yesterday i discovered that the problem was a cookie(header) that had an invalid char, I'm now trying to figure a way (if it's possible) to make kestrel ignore this invalid cookie(header)


That's work :)

**Comment by EdgarSalazar** [comment]
> yesterday i discovered that the problem was a cookie(header) that had an invalid char, I'm now trying to figure a way (if it's possible) to make kestrel ignore this invalid cookie(header)

Clearing cookies will solve the issue. Thanks.
