### ISSUE TITLE
Registration of INotificationHandler<> in the Ioc Container causes messages to be handled twice

### ISSUE THREAD

**Issue by gkrit** [EduardoPires/EquinoxProject#50]
in the Ioc project the following
services.AddScoped<INotificationHandler<RegisterNewCustomerCommand>, CustomerCommandHandler>();

causes the CustomerCommandHandler Handle method to run twice!

**Comment by thiagolunardi** [comment]
The IOC registration of command handler should be specific.

`services.AddScoped<INotificationHandler<RegisterNewCustomerCommand>, CustomerCommandHandler>();`

**Comment by EduardoPires** [comment]
I think Thiago answered your doubt!
