### ISSUE TITLE
Multiple RDBMS

### ISSUE THREAD

**Issue by kanpinar** [EduardoPires/EquinoxProject#51]
How to migrate to MySQL or 
use together MySQL and MsSQL

https://github.com/damienbod/AspNetCoreMultipleProject/tree/master/src/AspNetCoreMultipleProject

thanks for help.

**Comment by mstfcck** [comment]
I found a repository like this [Weapsy](https://github.com/Weapsy/Weapsy). It might give you an idea.

**Comment by thiagolunardi** [comment]
You just need to adapt the `CrossCutting.Data` project to it.

**Comment by m2017atTR** [comment]
Both are good tips... thanks.
