### ISSUE TITLE
Version 2 UI

### ISSUE THREAD

**Issue by jxvalenz** [EduardoPires/EquinoxProject#56]
Hello,
The road map mentions a new front end. Will it still be pure ASP.NET MVC or will you use a JavaScript framework?

Thanks, and can't wait for Version 2!

**Comment by EduardoPires** [comment]
I'll provide a SPA with Angular 4, I'll keep the MVC UI too doing the same thing.
Will be 2 flavors of UI.

**Comment by m2017atTR** [comment]
?

**Comment by chhinsras** [comment]
React is suggested
