### ISSUE TITLE
Email Queue

### ISSUE THREAD

**Issue by mtugnoli** [EduardoPires/EquinoxProject#57]
In the user register function It would be nice to add the email message to a db table queue
and a scheduled task that sends it,
this is to have a receipt for all outgoing messages

**Comment by kanpinar** [comment]
+1
Is that possible to do same for some commands that does need to done immediately.
hold command in a queue then execute when system is in better condition, for example at night..

**Comment by thiagolunardi** [comment]
Here are the steps to accomplish this:
1. Create a IEmailService interface in Domain;
2. At CustomerCreatedEvent handler, consume the IEmailService
3. Create a class library for the EmailService, add reference to Domain, implement a EmailService.
4. Registry the EmailService at IoC project to be added to the container.
5. Be happy.

**Comment by mtugnoli** [comment]
I think a Scheduling Task System is better,
It can also be used for other purposes like ..
- Clear log
- Keep alive
- Notifications
- Other things that have to be repetitive

**Comment by EduardoPires** [comment]
You can use HangFire to add tasks at queue, schedule and send the e-mail async.
HangFire have a dashboard that you can track the successful tasks and retry failed tasks. 

No windows service is required :)

https://www.hangfire.io/
