### ISSUE TITLE
Equinox.Application.AutoMapper.AutoMapperConfig.cs

### ISSUE THREAD

**Issue by liugt34** [EduardoPires/EquinoxProject#59]
hello,i have a question ?,How does this file work? i can't find an entry of this file?

or this file did't work ?

**Comment by Blener** [comment]
Hello.

AutoMapper searchs for any implementation of the MapperConfiguration when it's initialized, there's no need to call it.

**Comment by EduardoPires** [comment]
Actually this AutoMapperConfig file isn't necessary. It will removed in the next update.
The automapper discover automatically the Profile classes and initialize them.

In the v3 of AutoMapper.Extensions.Microsoft.DependencyInjection the discover isn't working I think was removed, you need to pass the profile classes at services.AddAutomapper(Profile1, Profile2);
