### ISSUE TITLE
ViewModels' validation

### ISSUE THREAD

**Issue by korzonkiee** [EduardoPires/EquinoxProject#60]
Hello,

Let's consider a scenario that we are creating new customer. If I understand correctly, `CustomerViewModel's` validation is performed firstly on object passed from POST, i.e. on `ModelState`.

[src/Equinox.Application/ViewModels/CustomerViewModel.cs](https://github.com/EduardoPires/EquinoxProject/blob/1fb072ac9c8096a2bad882f4562c5028cec5c953/src/Equinox.Application/ViewModels/CustomerViewModel.cs)

Then the `RegisterNewCustomerCommand` is executed and validation is performed using `RegisterNewCustomerCommandValidation`.

[src/Equinox.Domain/Validations/RegisterNewCustomerCommandValidation.cs](https://github.com/EduardoPires/EquinoxProject/blob/1fb072ac9c8096a2bad882f4562c5028cec5c953/src/Equinox.Domain/Validations/RegisterNewCustomerCommandValidation.cs)

I've noticed that there is a difference between the way that `CustomerViewModel` is being validated in the first step mentioned above and the second one - the name's max length differs.

[src/Equinox.Application/ViewModels/CustomerViewModel.cs#L14](https://github.com/EduardoPires/EquinoxProject/blob/1fb072ac9c8096a2bad882f4562c5028cec5c953/src/Equinox.Application/ViewModels/CustomerViewModel.cs#L14)
[src/Equinox.Domain/Validations/CustomerValidation.cs#L13](https://github.com/EduardoPires/EquinoxProject/blob/1fb072ac9c8096a2bad882f4562c5028cec5c953/src/Equinox.Domain/Validations/CustomerValidation.cs#L13)

I aware that it is trivial issue, but maybe it would be better to abstract those validation constants to some static class? Or maybe the validation step should be performed just once?

Please let me know what you think about it :smile:

Thanks.

**Comment by EduardoPires** [comment]
I can't figure out how use same logic for different approaches without create a lot of complexity.

About the length is right! Was a distraction.
The advantage of DataAnnotations is the validation in the Razor View it prevents unecessary hits in the server.

I will implement SPA and the client validations will be in JS and the server validations in the commands / models.

In the web development this double check is important.

**Comment by thiagolunardi** [comment]
This is a case that brought me to a decision to move all commands and events to Bus class library. 

- First, they don't have dependencies with domain;
- Second, a command should be the same - definition and validations - from the app services call to domain handlers. They as just messages, DTOs.

Then the commands can be created from anywhere, but just the app services has the ability to put them into the processing queue.

The same for the Events, anyhow can subscript to listening an event, not just the domain.
