### ISSUE TITLE
Repository pattern implementation need explanation 

### ISSUE THREAD

**Issue by binson143** [EduardoPires/EquinoxProject#63]
In the architecture we can  save the transaction by calling either
 _customerRepository.SaveChanges();  or   Commit();

Why repository needs SaveChanges ,the  uow pattern already  calling dbContext SaveChanges  methode 

Please give some clarification..

**Comment by EduardoPires** [comment]
We have this implementation due the case when you need to persist something without call the Commit of UoW. But if is unnecessary you can remove.
