### ISSUE TITLE
Environment Variables in DbContext

### ISSUE THREAD

**Issue by henry-rodriguez** [EduardoPires/EquinoxProject#64]
Hello,

I've been following this project and it appears that the EquinoxContext does not support multiple environment settings (appsettings.*.json) nor environment variables because it is set in the OnConfiguring override method of the EquinoxContext file instead of setting it up in the Equinox.Infra.CrossCutting.IoC.NativeInjectorBootstrapper.cs file.

Am i missing something? 
How would this project support multiple database environments, like DEV, STAGING, PROD?

Great project and set up by the way :-)

**Comment by EduardoPires** [comment]
I'll improve the support for N environments in the next version.

**Comment by gang89** [comment]
Hi guys, I am facing this issue too. 
Is there any reference solution at the mean time? would love to proceed with trying out a new project with this template. But this is currently a blocker :(

**Comment by EduardoPires** [comment]
The environment variables are located at startup and launchsettings, this is the correct way to proceed.
