### ISSUE TITLE
RegisterMappings why it's there?

### ISSUE THREAD

**Issue by fouadroumieh** [EduardoPires/EquinoxProject#66]
I don't see any call to the below method in the code, is it needed?
`public class AutoMapperConfig
    {
               
        public static MapperConfiguration RegisterMappings()
        {
            return new MapperConfiguration(cfg =>
            {
                cfg.AddProfile(new DomainToViewModelMappingProfile());
                cfg.AddProfile(new ViewModelToDomainMappingProfile());
            });
        }
    }`

**Comment by raptortrx** [comment]
When you call 
`services.AddAutoMapper();`
in Startup.cs AutoMapper searches automatically for Mapping Profiles and loads them on Application Startup.

**Comment by fouadroumieh** [comment]
@raptortrx thanks for your message but how this method is involved in that RegisterMappings?
Because I don't see any call for it.

**Comment by EduardoPires** [comment]
That is a dead code of an older implementation, it will be removed to avoid misunderstanding.

**Comment by EduardoPires** [comment]
@fouadroumieh After the last update the code remains because the automatic register only works if the profile class is in ASP.NET project assembly.
