### ISSUE TITLE
Why INotificationHandler not IRequestHandlers

### ISSUE THREAD

**Issue by fouadroumieh** [EduardoPires/EquinoxProject#68]
Why INotificationHandler was used instead of IRequestHandlers when Handling commands:

https://github.com/EduardoPires/EquinoxProject/blob/703c4d3e3cb37f675409b4fe66e649e48fc0c111/src/Equinox.Domain/CommandHandlers/CustomerCommandHandler.cs

The below thread show that IRequestHandlers is more for command and INotificationHandler for events type:

https://github.com/jbogard/MediatR/issues/163

**Comment by EduardoPires** [comment]
Improvement applied!
