### ISSUE TITLE
Unmapped members were found. Review the types and members below. AutoMapper.Extensions.Microsoft.DependencyInjection

### ISSUE THREAD

**Issue by muhammetsahin** [EduardoPires/EquinoxProject#70]
Hi,

I've got this error

`An unhandled exception occurred while processing the request.
AutoMapperConfigurationException: 
Unmapped members were found. Review the types and members below.
Add a custom mapping expression, ignore, add a custom resolver, or modify the source/destination type
For no matching constructor, add a no-arg ctor, add optional arguments, or map all of the constructor parameters

Unmapped properties:
Timestamp
ValidationResult
MessageType
AggregateId
AutoMapper.ConfigurationValidator.AssertConfigurationIsValid(IEnumerable<TypeMap> typeMaps)`

`  services.AddSingleton(Mapper.Configuration);
      services.AddScoped<IMapper>(sp => new Mapper(sp.GetRequiredService<IConfigurationProvider>(), sp.GetService));`

Any idea ?

**Comment by thiagolunardi** [comment]
Did you run migration Database Update?

**Comment by EduardoPires** [comment]
Closed by IDLE

**Comment by appsupport-gc** [comment]
Yes!  I found the solution:

Adding Ignore for each member:

 CreateMap<TestMe, TestMeDto>().ForMember(x => x.SomethingElse, opt => opt.Ignore());

Or changing validation to false

options.AddMaps<TheProblemApplicationModule>(validate: false);
