### ISSUE TITLE
How to perform a transaction which involves two entities?

### ISSUE THREAD

**Issue by murbanowicz** [EduardoPires/EquinoxProject#71]
Hi,

I was trying to figure it out but as this great project includes only one model there is no example of that.

How should I handle the process which involves creating 'a group' and assigning creator to this group?  In standard way I would just use simple transaction and transaction.rollback in case of failure but I cannot figure it out how should it be done using these patterns?

I would really appreciate help with understanding this problem.

**Comment by EduardoPires** [comment]
The command must have all information that you need. If you need to manipulate and change more than one entity do that in CommandHandler (with unit of work). You can publish new commands inside and Handler too.
