### ISSUE TITLE
MediatR issue

### ISSUE THREAD

**Issue by nicotravassos** [EduardoPires/EquinoxProject#72]
Hi,

I updated MediatR to its latest version and I am receiving this error below if anyone has also received this error please could you assist me on a fix.

![mediatr](https://user-images.githubusercontent.com/36132357/36244705-fd4af726-122f-11e8-958a-2b7c7bcf14f9.PNG)

![event](https://user-images.githubusercontent.com/36132357/36244726-0ec4d454-1230-11e8-8e9f-bdb4be168d51.PNG)

![event02](https://user-images.githubusercontent.com/36132357/36244739-1b1aa7ce-1230-11e8-87b7-58032e0f5fb1.PNG)

**Comment by kanpinar** [comment]
First Q ; Why needed to update version ??? 

Right Way ; 
As you know , Error clearly says that Interface is not implemented, 
Just click to yellow bulb then select Implement interface then fix not implemented yet exception part in newly created method ..

Best Solution For Your Situation ;
you can find in git and copy paste implemented source of same versions ;) i guess ..

Suggest; 
If you dont know, what are you doing; 
just return back to old versions on dependicies.. no shame on that.

**Comment by nicotravassos** [comment]
Thanks @kanpinar

**Comment by EduardoPires** [comment]
The v4 of MediatR have a break change.
I will update the project to use this version and you can check the new implementation.

**Comment by nicotravassos** [comment]
Thank you @EduardoPires much appreciated!

**Comment by nicotravassos** [comment]
@EduardoPires sorry to ask this but when can we expect the next release?

**Comment by afernandes** [comment]
```
public Task Handle(DomainNotification message, CancellationToken cancellationToken)
        {
            cancellationToken.ThrowIfCancellationRequested();

            _notifications.Add(message);

            return Task.CompletedTask;
        }
```
