### ISSUE TITLE
does not work Equinox.WebApi

### ISSUE THREAD

**Issue by novoselovr** [EduardoPires/EquinoxProject#73]
opens a blank page, the browser console error:
Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by kanpinar** [comment]
as far a i know, this solution using Swagger so 

          SwaggerEndpoint("/swagger/v1/swagger.json", "My API V1");

[https://swagger.io/](https://swagger.io/)
[https://docs.microsoft.com/en-us/aspnet/core/tutorials/web-api-help-pages-using-swagger?tabs=visual-studio](https://docs.microsoft.com/en-us/aspnet/core/tutorials/web-api-help-pages-using-swagger?tabs=visual-studio)


		services.AddWebApi(options =>
			{
				options.OutputFormatters.Remove(new XmlDataContractSerializerOutputFormatter());
				options.UseCentralRoutePrefix(new RouteAttribute("api/v{version}"));
			});
			
		services.AddSwaggerGen(s =>
		{
			s.SwaggerDoc("v1", new Info
			{
				Version = "v1",
				Title = "Equinox Project",
				Description = "Equinox API Swagger surface",
				Contact = new Contact { Name = "Eduardo Pires", Email = "contato@eduardopires.net.br", Url = "http://www.eduardopires.net.br" },
				License = new License { Name = "MIT", Url = "https://github.com/EduardoPires/EquinoxProject/blob/master/LICENSE" }
			});
		});

**Comment by EduardoPires** [comment]
You can edit the launchSettings.json to set your start page as Swagger page
