### ISSUE TITLE
New feature request: Saga

### ISSUE THREAD

**Issue by afernandes** [EduardoPires/EquinoxProject#74]
New feature request: implement saga for long-running business processes

**Example**
[https://blog.bernd-ruecker.com/saga-how-to-implement-complex-business-transactions-without-two-phase-commit-e00aa41a1b1b](https://blog.bernd-ruecker.com/saga-how-to-implement-complex-business-transactions-without-two-phase-commit-e00aa41a1b1b)

[https://docs.particular.net/nservicebus/sagas/](https://docs.particular.net/nservicebus/sagas/)

**Comment by alexsandro-xpt** [comment]
Masstransit or NServicebus?

https://stackoverflow.com/questions/13647423/nservicebus-vs-masstransit

I guess Masstransit is more attractive.

**Comment by marcrib** [comment]
Nem há situação no projeto atual para se usar saga.

**Comment by lawrenceong001** [comment]
Hello, 
just wondering if this has been implemented? I'm also interested in how this pattern can be achieved in your solution. 

tks
Lawrence

**Comment by EduardoPires** [comment]
At this moment the saga pattern doesn't fit with the project purpose
