### ISSUE TITLE
New feature request: Background Commands with MediatR and Hangfire

### ISSUE THREAD

**Issue by afernandes** [EduardoPires/EquinoxProject#75]
New feature request: Background Commands with MediatR and Hangfire

**Example**
[https://codeopinion.com/background-commands-mediatr-hangfire/](https://codeopinion.com/background-commands-mediatr-hangfire/)

[https://github.com/dcomartin/Hangfire.MediatR.Demo](https://github.com/dcomartin/Hangfire.MediatR.Demo)

**Comment by alexsandro-xpt** [comment]
@afernandes Why add a hangfire feature? Some benefits?

**Comment by EduardoPires** [comment]
It's a good thing, but I can not see this necessity in this project at this time.
