### ISSUE TITLE
PM> Update-Database (error)

### ISSUE THREAD

**Issue by afernandes** [EduardoPires/EquinoxProject#77]
Applying migration '20161206204752_Initial' error.
An object named 'AspNetUsers' already exists in the database.

**Comment by TeoDanilo** [comment]
It aways accours to me. Idk why but I can never update the database, I aways need to delete the DB to use the Update-database when I test this solution to learn from Eduardo. I really fear to use dbfirst in big projetcts.

**Comment by afernandes** [comment]
I got it resolved!
The tables were being created in two places.

Equinox.Infra.CrossCutting.Identity\Data\Migrations\00000000000000_CreateIdentitySchema.cs

AND

Equinox.Infra.CrossCutting.Identity\Migrations\20161206204752_Initial.cs
