### ISSUE TITLE
Using the "Include" on GetAll method

### ISSUE THREAD

**Issue by marcelojaf** [EduardoPires/EquinoxProject#78]
Hi Eduardo,

If we consider that the Customer entity has a list of another entity like IEnumerable<Address> AddressList;. At the CustomerController, when I use GetAll(), how can I use the Include() to fill the AddressList ?? Is there a way that I can override the GetAll method?

Thank you

**Comment by kanpinar** [comment]
There is a project on github

https://github.com/digipolisantwerp/dataaccess_aspnetcore

i think good one to Paging include ext. , this kind problems. 
Also can easyly integrate this project. 
I am using it with mysql with Equinox

**Comment by OzBob** [comment]
It's in aspnet core 2.1
Upgrade?
That'd be a good feature request ...

**Comment by OzBob** [comment]
Further EF Core features (include for derived types) https://blogs.msdn.microsoft.com/dotnet/2018/02/27/announcing-entity-framework-core-2-1-preview-1/

**Comment by EduardoPires** [comment]
The new improvements took care of that.
