### ISSUE TITLE
Error - Not Support Targeting .Net Core 2.0

### ISSUE THREAD

**Issue by brunohbrito** [EduardoPires/EquinoxProject#80]
I was getting this message while trying to build: **"The current .NET SDK does not support targeting .NET Core 2.0.  Either target .NET Core 1.1 or lower, or use a version of the .NET SDK that supports .NET Core 2.0."**

After some hours looking, I got the problem at global.json:

`
{
  "projects": [ "src", "test" ],
  "sdk": {
    "version": "2.0.3"
  }
}
`
So just removing Sdk option, everything goes fine.

This error was occurring 'cause a fresh new installation of my windows and after get the new SDK, it didn't come with 2.0 version of SDK.

asap I'll make a pull Request

**Comment by tanushshukla** [comment]
thanks. you saved me a day.

**Comment by EduardoPires** [comment]
In this case we have 2 options:

-1 Install the last version of SDK and adjust the global.json with the version number

-2 Remove or comment the content of global.json (But the code will works with the SDK on machine, maybe you will get some errors).

My recommendation is the 1 option.
