### ISSUE TITLE
Upgrade to use new version 4.x of MediatR

### ISSUE THREAD

**Issue by frostholmft** [EduardoPires/EquinoxProject#82]
Some major changes was made to MediatR could you make the project adapt to these changes ?

What is the status on the release plan, i seems postponed ?

**Comment by nicotravassos** [comment]
@frostholmft I have asked @EduardoPires the same question. I would not count on release anytime soon.

Just keep MediatR @ v2.0.0 until he releases something.

**Comment by EduardoPires** [comment]
@ghost
"Just keep MediatR @ v2.0.0 until he releases something."  - It's right!

In some days I'll update all the code :)
