### ISSUE TITLE
AutoMapper unmaped properties

### ISSUE THREAD

**Issue by abnerorlamunder** [EduardoPires/EquinoxProject#83]
Quando tento utilizar o mapeamento de ViewModel para Command ele da erro informando que há propriedades no Command que não existem no ViewModel, e realmente há, porém como faço para ignorá-los? Achei a seguinte forma, porém não funcionou:

.ForMember(c => c.Timestamp, opt => opt.Ignore())
.ForMember(c => c.ValidationResult, opt => opt.Ignore())
.ForMember(c => c.MessageType, opt => opt.Ignore())
.ForMember(c => c.AggregateId, opt => opt.Ignore());

------------

Unmapped members were found. Review the types and members below.
Add a custom mapping expression, ignore, add a custom resolver, or modify the source/destination type
For no matching constructor, add a no-arg ctor, add optional arguments, or map all of the constructor parameters
=================================================================================================
VehicleViewModel -> RegisterNewVehicleCommand (Destination member list)
D1Web.Application.ViewModels.VehicleViewModel -> D1Web.Domain.Commands.RegisterNewVehicleCommand (Destination member list)

Unmapped properties:
Timestamp
ValidationResult
MessageType
AggregateId

**Comment by EduardoPires** [comment]
It's because automapper didn't found your mapping profiles, see the last change in this project (today) in Startup.cs

**Comment by MehdiSheykhveysi** [comment]
You can resolve your ٍError through this link  [https://stackoverflow.com/questions/27359999/auto-mapper-unmapped-members-were-found](url)
