### ISSUE TITLE
Are the view models the domain models?

### ISSUE THREAD

**Issue by VictorioBerra** [EduardoPires/EquinoxProject#87]
I see that the service in the app layer maps ef entities to view models. In my app, I have an extra layer where my repos never return entities but only domain models.

Also whats the major difference between Domain and Domain.Core?

**Comment by EduardoPires** [comment]
ViewModels aren't Domain Models. ViewModels is like a DTO to transport data and care about forms validation at the View.

The Domain.Core is a common domain, like a shared kernel.
