### ISSUE TITLE
Question about Column Names

### ISSUE THREAD

**Issue by TeoDanilo** [EduardoPires/EquinoxProject#88]
Question: if I try to implement a "product" page (like in yout tutorial about DDD) and 'give' some products to a customer, would have problem if both use a guid caled "Id" instead of "ProductId" and "CustomerID" (or simply share same comlumn names)? If I change the names to ProductId and CustomerId would i have to change some generic code?

**Comment by EduardoPires** [comment]
If you want you can use any name in the PK, but using "ID" you will have some design facilities. You can observe this on the Entity base class.

**Comment by TeoDanilo** [comment]
Thank you, now that you said i realized that i did never open the entity base class, in fact i did not open anything inside domain.core until your answer. My bad. Thank you again
