### ISSUE TITLE
it can not run on the new dotnet sdk-2.1.200-win-x64

### ISSUE THREAD

**Issue by liugt34** [EduardoPires/EquinoxProject#90]
i had update the sdk to the new version "dotnet-sdk-2.1.200-win-x64",but i can't run anymore

i find the issue

![image](https://user-images.githubusercontent.com/8056013/40302231-fc877a44-5d20-11e8-92b6-6dce4bbfdb88.png)

**Comment by EduardoPires** [comment]
It's running normally.

Try to change global.json with the correct version of SDK.

Post some error message.
