### ISSUE TITLE
Task Scheduling

### ISSUE THREAD

**Issue by mtugnoli** [EduardoPires/EquinoxProject#92]
Hi, It would be nice to have a scheduling task system in the next version,
best if the list of tasks are stored in db.
ex. Send emails,Keep alive, Clear log

**Comment by EduardoPires** [comment]
I'll do that with HangFire

**Comment by btastic** [comment]
Have you seen https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/multi-container-microservice-net-applications/background-tasks-with-ihostedservice?

Maybe it is worth going for native EF Core utility classes than third party?

**Comment by lhmiranda** [comment]
IHostedService is cool but you will still have to deal with all the hassle of managing your tasks.
Also, the latest beta version of Hangfire already registers it as a Hosted Service (https://github.com/HangfireIO/Hangfire/issues/962).

**Comment by CanMehmetK** [comment]
I was trying it...
When researching, found kamil has some words about subject.
http://www.kamilgrzybek.com/design/processing-commands-with-hangfire-and-mediatr/

**Comment by EduardoPires** [comment]
You can use Hangfire or Background services (native)
