### ISSUE TITLE
Implement transactions

### ISSUE THREAD

**Issue by knuxbbs** [EduardoPires/EquinoxProject#93]
Despite the disclaimer, this project has a serious limitation: because it has multiple contexts, it's impossible to create transactions that involves more than one context.

It would be interesting to have a solution to this .NET Core limitation. Also due to the Identity isolation.

**Comment by EduardoPires** [comment]
You can't have consistency with many contexts or services. Forget about transactions. 
Read about CAP Theorem:

https://en.wikipedia.org/wiki/CAP_theorem
