### ISSUE TITLE
Question: Best way to handle multiple entities depending on each other

### ISSUE THREAD

**Issue by btastic** [EduardoPires/EquinoxProject#94]
Hey there,

first off, great repository. Learned a lot! However, right now I am tackling a problem which I don't have a definitive answer to.

I have CreateCustomerCommand which will be handled by a CustomerCommandHandler. 

The customer command has some other information, lets say an address. I want to store that address via a address repository.

How would I go about that?

Right now I thought about 2 ways:
- Inject the address repository, create an address object and add it to the address repository. Commit() will handle both.
- Send another command "AddCustomerAddressCommand" from the CustomerCommandHandler which will then be handled by a AddressCommandHandler and will get saved there.

Maybe there is a third way I am not thinking of. Would love to learn about a good solution to this.

Thank you!

**Comment by EduardoPires** [comment]
Depends. If Customer is a AggregationRoot and Address is part of this aggregation you need to have just one repository for this entities. Also my recommendation is add address in Customer AddressCollection and save both at the same time by EF. To edit or remove Address you can use more commands and the same customerHandler.

If Address is not part of Customer aggregation you can send a new command to handle de address when you are saving the customer.
