### ISSUE TITLE
ICustomerRepository & IEventStore using separate transactions

### ISSUE THREAD

**Issue by jernejg** [EduardoPires/EquinoxProject#96]
Hi Eduardo,

What are your thoughts on modifying the Customers and the StoredEvent in the same transaction ?

The way I understand ES is that the Event table acts as a source of truth from which you can determine the application state at any point in time, so we first need to guarantee the insertion to the Events table and then modify the current snapshot which is the Customers table.

Thanks for your answer.

**Comment by EduardoPires** [comment]
There's no reason to do that. Events is always in the past... If the app had a problem to persist the event will be necessary some check system to retry.
